---
# Common packages to be installed on all systems
package_management_common_install_packages:
  - autoconf
  - bash
  - bison
  - ca-certificates
  - colordiff
  - dbus-x11
  - file
  - gcc
  - git
  - less
  - make
  - net-tools
  - procps
  - rsync
  - sudo
  - terminator
  - tree
  - unzip
  - vim
  - wget
  - zsh

# Conditional assignment based on OS family
package_management_install_packages: "{{ (ansible_os_family == 'Debian') | ternary(package_management_debian_specific_packages, package_management_redhat_specific_packages) }}"

# Debian-specific packages
package_management_debian_specific_packages:
  - build-essential
  - curl
  - fonts-powerline
  - inetutils-ping
  - libdb-dev
  - libffi-dev
  - libgdbm-dev
  - libgdbm6
  - libncurses5-dev
  - libreadline6-dev
  - libssl-dev
  - libyaml-dev
  - locales
  - software-properties-common
  - tigervnc-standalone-server
  - tigervnc-tools
  - xfce4-goodies
  - xfce4
  - zlib1g-dev
  - zsh-autosuggestions

# RedHat-specific packages
package_management_redhat_specific_packages:
  - bzip2-devel
  - epel-release
  - gcc
  - gcc-c++
  - libffi-devel
  - libtool
  - openssl-devel
  - readline-devel
  - sqlite-devel
  - tigervnc
  - tigervnc-server
  - zlib-devel
