---
- name: RunZero Explorer
  hosts: all
  roles:
    - role: cowdogmoo.workstation.user_setup
    - role: cowdogmoo.workstation.package_management
    - role: cowdogmoo.workstation.runzero_explorer
