---
# Use Ansible Galaxy to install dependencies
dependency:
  name: galaxy
  options:
    # Install required galaxy roles
    role-file: ../../requirements.yml
    # Install required collections
    requirements-file: ../../requirements.yml

# Run molecule inside of a docker container
driver:
  name: docker

platforms:
  - name: ubuntu-vnc_box
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    hostname: ubuntu-vnc_box
    extra_hosts:
      - "ubuntu-vnc_box:127.0.1.1"

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

verifier:
  name: ansible
