---
- name: Merge common and OS-specific install packages
  ansible.builtin.set_fact:
    package_management_common_install_packages: "{{ package_management_common_install_packages + (package_management_debian_install_packages | default([])) }}"

- name: Install packages (Debian)
  become: true
  ansible.builtin.package:
    name: "{{ package_management_common_install_packages }}"
    state: present
    update_cache: true
  environment:
    DEBIAN_FRONTEND: noninteractive
