---
- name: Include common variables
  ansible.builtin.include_vars: "main.yml"

- include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Cleanup packages
  become: true
  ansible.builtin.package:
    name: "{{ package_management_common_cleanup_packages }}"
    state: absent
  environment: "{{ (ansible_os_family == 'Debian') | ternary({'DEBIAN_FRONTEND': 'noninteractive'}, {}) }}"
