---
- name: Install packages (Debian)
  become: true
  ansible.builtin.package:
    name: "{{ package_management_install_packages }}"
    state: present
    update_cache: true
  environment:
    DEBIAN_FRONTEND: noninteractive
