---
- name: Install special Red Hat packages
  become: true
  ansible.builtin.dnf:
    name: "{{ package_management_install_packages }}"
    state: present

- name: Configure .xinitrc for XFCE (Red Hat)
  become: true
  ansible.builtin.copy:
    dest: "~/.xinitrc"
    content: "exec /usr/bin/xfce4-session"
    mode: "0644"

- name: Get current systemd default target (Red Hat)
  ansible.builtin.command:
    cmd: systemctl get-default
  register: systemd_units
  check_mode: false
  changed_when: false
  # noqa command-instead-of-module

- name: Set default target to graphical if not already set (Red Hat)
  ansible.builtin.systemd:
    name: graphical.target
    state: started
  when: "'graphical.target' not in systemd_units.stdout"

- name: Install packages (Red Hat)
  become: true
  ansible.builtin.dnf:
    name: "{{ package_management_common_install_packages }}"
    state: present
