---
- name: Install special Red Hat packages
  become: true
  ansible.builtin.dnf:
    name: "{{ package_management_install_packages }}"
    state: present

- name: Configure .xinitrc for XFCE (Red Hat)
  become: true
  ansible.builtin.copy:
    dest: "~/.xinitrc"
    content: "exec /usr/bin/xfce4-session"
    mode: "0644"

- name: Set fact for current default target (Red Hat)
  ansible.builtin.set_fact:
    is_graphical_default: "{{ 'graphical.target' in systemd_units.stdout }}"

- name: Set default target to graphical (Red Hat)
  ansible.builtin.systemd:
    name: graphical.target
    state: started
  when: not is_graphical_default

- name: Install packages (Red Hat)
  become: true
  ansible.builtin.dnf:
    name: "{{ package_management_common_install_packages }}"
    state: present
