---
- name: Determine runzero-explorer binary architecture
  ansible.builtin.set_fact:
    runzero_explorer_arch: "{{ runzero_explorer_arch_map[ansible_architecture] | default('amd64') }}"
  when: ansible_os_family in ['Debian', 'RedHat', 'Darwin', 'Windows']

- name: Set default value for runzero_explorer_dest
  ansible.builtin.set_fact:
    runzero_explorer_dest: "{{ runzero_explorer_default_dest }}"
  when: runzero_explorer_dest is not defined and ansible_os_family != 'Windows'

- name: Include tasks for Unix-like systems
  ansible.builtin.include_tasks: unix.yml
  when: ansible_os_family in ['Debian', 'RedHat', 'Darwin']

- name: Include systemctl tasks
  ansible.builtin.include_tasks: systemctl.yml
  when: ansible_os_family in ['Debian', 'RedHat', 'Darwin'] and runzero_explorer_systemd_enabled | bool

- name: Include tasks for Windows
  ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
