---
- name: Set runzero-explorer download URL for Unix-like systems
  ansible.builtin.set_fact:
    runzero_explorer_url: "{{ runzero_explorer_url_base }}/runzero-explorer-linux-{{ runzero_explorer_arch }}.bin"
  when: ansible_os_family in ['Debian', 'RedHat']

- name: Set runzero-explorer download URL for Darwin systems
  ansible.builtin.set_fact:
    runzero_explorer_url: "{{ runzero_explorer_url_base }}/runzero-explorer-darwin-{{ runzero_explorer_arch }}.bin"
  when: ansible_os_family == 'Darwin'

- name: Create runZero Explorer directory
  ansible.builtin.file:
    path: "{{ runzero_explorer_default_dest | dirname }}"
    state: directory
    mode: '0755'
  become: true

- name: Check if runzero-explorer already exists
  ansible.builtin.stat:
    path: "{{ runzero_explorer_dest }}"
  register: runzero_explorer_file

- name: Download runzero-explorer
  ansible.builtin.get_url:
    url: "{{ runzero_explorer_url }}"
    dest: "{{ runzero_explorer_dest }}"
    mode: '0755'
  when: not runzero_explorer_file.stat.exists

- name: Find runzero-agent files
  ansible.builtin.find:
    paths: "{{ runzero_explorer_dest }}"
    patterns: "runzero-agent-*"
  register: runzero_agent_files

- name: Rename runzero-explorer to default destination
  ansible.builtin.command:
    cmd: "mv {{ item.path }} {{ runzero_explorer_default_dest }}"
  loop: "{{ runzero_agent_files.files }}"
  when: runzero_agent_files.matched > 0 and not runzero_explorer_file.stat.exists
  changed_when: true


- name: Execute runzero-explorer
  become: true
  ansible.builtin.command:
    cmd: "{{ runzero_explorer_dest }}"
  changed_when: false
