---
namespace: cowdogmoo
name: workstation
version: "1.9.1"
readme: README.md
authors:
  - Jayson Grace <techvomit.net>
description: Install and configure utilities and applications that I employ regularly.
license_file: "LICENSE"
tags: [asdf, linux, logrotate, tools, runzero, vnc, zsh]
repository: https://github.com/CowDogMoo/ansible-collection-workstation
issues: https://github.com/CowDogMoo/ansible-collection-workstation/issues
