---
- name: Provision linux workstation
  hosts: cowdogmoo
  environment:
    DEBIAN_FRONTEND: noninteractive

  tasks:
    - name: Install packages
      become: yes
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ install_packages }}"
      when: ansible_os_family == "Debian"

    - name: Install pip packages
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      loop: "{{ pip_packages }}"

    - name: Download homebrew installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
        dest: /tmp/brew-installer.sh
        mode: "0755"
      changed_when: false

    - name: Install homebrew
      ansible.builtin.command: /tmp/install.sh
      become: yes
      become_method: su
      become_user: "{{ normal_user }}"
      changed_when: false

    - name: Add homebrew to $PATH
      become: yes
      ansible.builtin.blockinfile:
        insertafter: EOF
        path: "{{ target_dotfile }}"
        block: "{{ lookup('template', 'install_brew.j2') }}"
        marker: ""
      changed_when: false

    - name: Execute the brew-installer.sh
      shell: /tmp/brew-installer.sh

    - name: Clean up installation script
      ansible.builtin.file:
        path: /tmp/brew-installer.sh
        state: absent
      changed_when: false
