---
galaxy_info:
  role_name: go_task
  namespace: cowdogmoo
  author: Jayson Grace
  description: Installs go-task (Task runner) on Unix-like and Windows systems
  company: CowDogMoo
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: MacOSX
      versions:
        - all
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - task
    - taskfile
    - gotask
    - automation
    - build
dependencies: []
