---
galaxy_info:
  author: Jayson Grace
  namespace: cowdogmoo
  description: Installs VNC and zsh running with oh-my-zsh on debian-based systems.
  company: CowDogMoo
  license: MIT
  role_name: asdf
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: macOS
      versions:
        - all
    - name: Windows
      versions:
        - all

