---
galaxy_info:
  role_name: asdf
  namespace: cowdogmoo
  author: Jayson Grace
  description: Install asdf and associated dependencies"
  company: CowDogMoo
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: macOS
      versions:
        - all
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - asdf
