---
- name: Converge
  hosts: all
  roles:
    - role: cowdogmoo.workstation.user_setup
    - role: cowdogmoo.workstation.package_management
    - role: cowdogmoo.workstation.zsh_setup
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
