objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    merge_list_dicts_into_list:
      description: Manage VNC passwords for users.
      name: merge_list_dicts_into_list
      namespace: "CowdogMoo"
      version_added: null
    vnc_pw:
      description: Merge list of dictionaries with a list.
      name: vnc_pw
      namespace: "CowdogMoo"
      version_added: null
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.2.0
