---
changelog_filename_template: CHANGELOG.rst
changes_file: changelog.yaml
changes_format: combined
keep_fragments: false
mention_ancestor: true
namespace: CowDogMoo
new_plugins_after_name: removed_features
notesdir: fragments
prelude_section_name: release_summary
prelude_section_title: Release Summary
sanitize_changelog: true
sections:
  - ["added", "Added"]
  - ["changed", "Changed"]
  - ["removed", "Removed"]
  - ["fixed", "Fixed"]
title: cowdogmoo.workstation
trivial_section_name: trivial
use_fqcn: true
