---
changelog_filename_template: CHANGELOG.rst
changelog_filename_version_depth: 0
changes_file: changelog.yaml
changes_format: combined
ignore_other_fragment_extensions: true
keep_fragments: no
archive_path_template: changelogs/fragments/archived/{version}
mention_ancestor: true
new_plugins_after_name: removed_features
notesdir: fragments
prelude_section_name: release_summary
prelude_section_title: Release Summary
sanitize_changelog: true
sections:
  - - added
    - Added
  - - changed
    - Changed
  - - removed
    - Removed
  - - fixed
    - Fixed
title: cowdogmoo.workstation
trivial_section_name: trivial
use_fqcn: true
