---
# Default username and group are set based on the operating system
zsh_setup_default_username: "{{ ansible_env.USER if ansible_os_family == 'Darwin' else ansible_distribution | lower }}"
zsh_setup_default_group: "{{ 'staff' if ansible_os_family == 'Darwin' else ansible_distribution | lower }}"

# Oh My ZSH install script URL
zsh_setup_omz_install_script_url: "https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh"
