---
- name: Gather the list of unique shells to install
  ansible.builtin.set_fact:
    unique_shells: "{{ user_setup_default_users | map(attribute='shell') | unique | list }}"
  tags: always

- name: Install base packages
  become: true
  ansible.builtin.dnf:
    name: "{{ user_setup_install_packages }}"
    state: present
    update_cache: true
  tags: packages

- name: Install user-specific shells
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ unique_shells }}"
  when: item != '' and item != '/bin/bash'
  tags: shells
