---
- name: Ensure users exist and have home directories
  become: true
  ansible.builtin.user:
    name: "{{ item.username }}"
    group: "{{ item.usergroup }}"
    shell: "{{ item.shell }}"
    create_home: true
    home: "{{ '/Users' if ansible_os_family == 'Darwin' else '/home' }}/{{ item.username }}"
  register: user_info
  loop: "{{ user_setup_default_users }}"
  loop_control:
    label: "{{ item.username }}"
  tags: user-setup
  when: ansible_os_family != 'Darwin'

- name: Update home_path for all users
  ansible.builtin.set_fact:
    enriched_asdf_enriched_users: >-
      {{ (enriched_asdf_enriched_users | default([])) |
      rejectattr('username', 'equalto', item.item.username) | list +
      [item.item | combine({
        'home_path': item.home,
        'shell_profile_lines': [
          "export ASDF_DIR=$HOME/.asdf",
          "source $ASDF_DIR/asdf.sh"
        ]
        })] | selectattr('home_path', 'defined') | list }}
  loop: "{{ user_info.results }}"
  loop_control:
    label: "{{ item.item.username }}"
