---
- name: Update home for all users
  ansible.builtin.set_fact:
    enriched_asdf_enriched_users: >-
      {{ (enriched_asdf_enriched_users | default([])) |
      rejectattr('username', 'equalto', item.username) | list +
      [item.item | combine({
        'home': item.home,
        'shell_profile_lines': [
          "export ASDF_DIR=$HOME/.asdf",
          "source $ASDF_DIR/asdf.sh"
        ]
        })] | selectattr('home', 'defined') | list }}
  loop: "{{ asdf_users }}"
