---
- name: Gather available local users
  ansible.builtin.getent:
    database: passwd
  register: getent_passwd
  when: ansible_os_family != 'Darwin'

- name: Gather available local users on macOS
  cowdogmoo.workstation.getent_passwd:
  register: getent_passwd
  when: ansible_os_family == 'Darwin'

- name: Initialize asdf_enriched_users
  ansible.builtin.set_fact:
    asdf_enriched_users: []

- name: Update home for all users
  ansible.builtin.set_fact:
    asdf_enriched_users: >-
      {{ (asdf_enriched_users | default([])) |
      rejectattr('username', 'equalto', item.username) | list +
      [item | combine({
        'home': ansible_facts.getent_passwd[item.username][4] if item.username in ansible_facts.getent_passwd else item.home,
        'shell_profile_lines': [
          "export ASDF_DIR=$HOME/.asdf",
          "source $ASDF_DIR/asdf.sh"
        ]
        })] | selectattr('home', 'defined') | list }}
  loop: "{{ asdf_users }}"
  when:
    - item.username in ansible_facts.getent_passwd
    - item.username != 'root'

- name: Ensure user home directory exists
  ansible.builtin.file:
    path: "{{ item.home }}"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.usergroup | default(item.username) }}"
    mode: '0755'
  loop: "{{ asdf_enriched_users }}"
  when:
    - item.username in ansible_facts.getent_passwd
    - item.username != 'root'
