---
- name: Gather available local users
  ansible.builtin.getent:
    database: passwd
  register: getent_passwd
  when: ansible_os_family != 'Darwin'

- name: Gather available local users on macOS
  cowdogmoo.workstation.getent_passwd:
  register: getent_passwd
  when: ansible_os_family == 'Darwin'

- name: Initialize asdf_enriched_users
  ansible.builtin.set_fact:
    asdf_enriched_users: []

- name: Update home for all users
  ansible.builtin.set_fact:
    asdf_enriched_users: >-
      {{ (asdf_enriched_users | default([])) +
         [user | combine({
           'home': ansible_facts.getent_passwd[user.username][4] if user.username in ansible_facts.getent_passwd else user.home,
           'shell_profile_lines': [
             "export ASDF_DIR=$HOME/.asdf",
             "source $ASDF_DIR/asdf.sh"
           ]
         })] | selectattr('home', 'defined') | list }}
  loop: "{{ asdf_users }}"
  loop_control:
    loop_var: user
  when:
    - user.username in ansible_facts.getent_passwd

- name: Ensure user home directory exists
  ansible.builtin.include_tasks: ensure_directory_exists.yml
  args:
    apply:
      become: "{{ ansible_facts['os_family'] != 'Darwin' }}"
  vars:
    directories:
      - path: "{{ user.home }}"
        owner: "{{ user.username }}"
        group: "{{ user.usergroup | default(user.username) }}"
        mode: '0755'
  loop: "{{ asdf_enriched_users }}"
  loop_control:
    loop_var: user
  when:
    - user.username in ansible_facts.getent_passwd
