---
- name: Get home directory for each user
  ansible.builtin.shell: >
    set -o pipefail
    getent passwd {{ item.username }} | cut -d: -f6
  register: home_dirs
  loop: "{{ asdf_users }}"
  changed_when: false

- name: Update home_path, shell, and plugins for each user in asdf_users
  ansible.builtin.set_fact:
    enriched_asdf_enriched_users: >-
      {{ (enriched_asdf_enriched_users | default([])) | rejectattr('username', 'equalto', item.0.username) | list +
      [item.0 | combine({
        'home_path': item.1.stdout,
        'shell': (item.0.shell | default('/bin/bash')),
        'shell_profile_lines': [
          'export ASDF_PATH="' + item.1.stdout + '/.asdf"',
          'export PATH="$ASDF_PATH/bin:$ASDF_PATH/shims:$PATH"',
          '. "$ASDF_PATH/asdf.sh"'
        ] if item.0.shell == '/bin/bash' else [
          'export ASDF_PATH="' + item.1.stdout + '/.asdf"',
          'export PATH="$ASDF_PATH/bin:$ASDF_PATH/shims:$PATH"',
          '. "$ASDF_PATH/asdf.sh"',
          'source $HOME/.asdf/asdf.sh'
        ]})] }}
  loop: "{{ asdf_users | zip(home_dirs.results) }}"
