---
- name: Iterate over users and setup scripts
  ansible.builtin.include_tasks: script_check_and_download.yml
  loop: "{{ asdf_users | subelements('asdf_setup_scripts') }}"
  loop_control:
    loop_var: user_script_pair
  vars:
    asdf_user: "{{ user_script_pair.0 }}"
    script_item: "{{ user_script_pair.1 }}"
