---
- name: Check if script exists
  ansible.builtin.stat:
    path: "{{ script_item.path }}"
  register: script_stat
  loop: "{{ asdf_user.asdf_setup_scripts }}"
  loop_control:
    loop_var: script_item

- name: Download script if not present
  ansible.builtin.get_url:
    url: "{{ script_item.url }}"
    dest: "{{ script_item.path }}"
    mode: "0644"
  when: script_stat.results | map(attribute='stat.exists') | list | select('equalto', false) | list | length > 0
  loop: "{{ asdf_user.asdf_setup_scripts }}"
  loop_control:
    loop_var: script_item
