---
- name: Check if item exists locally
  ansible.builtin.stat:
    path: "{{ item.path }}"
  register: script_stat

- name: Download item
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.path }}"
    mode: "0644"
  when: not script_stat.stat.exists
  failed_when: ansible_failed_result is defined and "Failed to download" in ansible_failed_result.msg
