---
- name: Ensure directory exists
  ansible.builtin.file:
    path: "{{ dir.path }}"
    state: directory
    owner: "{{ dir.owner }}"
    group: "{{ dir.group }}"
    mode: "{{ dir.mode | default('0755') }}"
  become: true
  loop: "{{ directories }}"
  loop_control:
    loop_var: dir
