---
- name: Get available versions for plugins
  ansible.builtin.shell: |
    export ASDF_DATA_DIR="{{ ansible_env.HOME }}/.asdf"
    export PATH="{{ ansible_env.HOME }}/.asdf/bin:{{ ansible_env.HOME }}/.asdf/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
    if [ ! -f "$ASDF_DATA_DIR/asdf.sh" ]; then
      echo "ASDF not properly initialized" >&2
      exit 1
    fi
    
    . "$ASDF_DATA_DIR/asdf.sh"
    
    if ! command -v asdf >/dev/null 2>&1; then
      echo "ASDF command not found" >&2
      exit 1
    fi
    
    # Add plugin if not exists
    if ! asdf plugin list | grep -q "{{ plugin.name }}"; then
      asdf plugin add "{{ plugin.name }}"
    fi
    
    # Get latest version
    asdf list-all "{{ plugin.name }}" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | tail -n 1
  register: available_version
  changed_when: false
  become: true
  become_user: "{{ asdf_username }}"