---
- name: Get available versions for plugins
  ansible.builtin.shell: |
    set -o pipefail
    export ASDF_DIR="{{ ansible_env.HOME }}/.asdf"
    export PATH="${ASDF_DIR}/bin:${ASDF_DIR}/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    if [ ! -f "${ASDF_DIR}/asdf.sh" ]; then
      echo "ASDF not properly initialized" >&2
      exit 1
    fi
    . "${ASDF_DIR}/asdf.sh"
    if ! command -v asdf >/dev/null 2>&1; then
      echo "ASDF command not found" >&2
      exit 1
    fi
    if ! asdf plugin list | grep -q "{{ plugin.name }}"; then
      asdf plugin add "{{ plugin.name }}"
    fi
    asdf list-all "{{ plugin.name }}" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | tail -n 1
  changed_when: false
