---
- name: Set default username for Kali systems
  ansible.builtin.set_fact:
    asdf_default_username: "kali"
  when: ansible_distribution_release == "kali-rolling" and asdf_default_username is not defined

- name: Include asdf_get_enriched_users tasks
  ansible.builtin.include_tasks: asdf_get_enriched_users.yml

- name: Clone asdf for each user
  ansible.builtin.git:
    repo: "{{ asdf_git_repo }}"
    dest: "{{ item.home_path }}/.asdf"
    clone: true
    update: false
  loop: "{{ enriched_asdf_enriched_users }}"
  when:
    - item.username != 'root'

- name: Deploy .tool-versions file
  ansible.builtin.template:
    src: tool-versions.j2
    dest: "{{ item.home_path }}/.tool-versions"
    owner: "{{ item.username }}"
    group: "{{ item.usergroup | default(item.username) }}"
    mode: "0644"
  loop: "{{ enriched_asdf_enriched_users }}"
  when:
    - item.username != 'root'

- name: Ensure correct permissions for .tool-versions
  ansible.builtin.file:
    path: "{{ item.home_path }}/.tool-versions"
    owner: "{{ item.username }}"
    group: "{{ item.usergroup | default(item.username) }}"
    mode: "0644"
  loop: "{{ enriched_asdf_enriched_users }}"
  when:
    - item.username != 'root'

- name: Ensure .asdf directory exists for each user
  ansible.builtin.file:
    path: "{{ item.home_path }}/.asdf"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.usergroup | default(item.username) }}"
    mode: "0755"
  loop: "{{ enriched_asdf_enriched_users }}"
  when:
    - item.username != 'root'

- name: Set permissions for each user's ASDF directory
  ansible.builtin.file:
    path: "{{ item.home_path }}/.asdf"
    owner: "{{ item.username }}"
    group: "{{ item.usergroup | default(item.username) }}"
    recurse: true
  loop: "{{ enriched_asdf_enriched_users }}"
  when:
    - item.username != 'root'

- name: Include task to update shell profiles for each user
  ansible.builtin.include_tasks: update_shell_profiles.yml
  loop: "{{ enriched_asdf_enriched_users }}"
  loop_control:
    loop_var: user
  vars:
    line: "{{ user.shell_profile_lines }}"
  when: user.username != 'root'

- name: Gather installed ASDF plugins and versions for each user
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      if [ -f "{{ item.home_path }}/.asdf/asdf.sh" ]; then
        . "{{ item.home_path }}/.asdf/asdf.sh"
      fi
      {% for plugin in item.plugins %}
      if ! asdf plugin list | grep -q {{ plugin.name }}; then
        asdf plugin add {{ plugin.name }};
      fi;
      {% endfor %}
      echo "plugins:$(asdf plugin list),versions:$(asdf list all | tr '\n' ',')"
    executable: "{{ item.shell }}"
  register: asdf_info
  changed_when: false
  become: true
  become_user: "{{ item.username }}"
  loop: "{{ enriched_asdf_enriched_users }}"

- name: Copy setup_asdf_env.sh to a common location for all users
  ansible.builtin.copy:
    src: setup_asdf_env.sh
    dest: "{{ asdf_install_script_path }}"
    mode: "0755"

- name: Install libyaml from source
  ansible.builtin.include_tasks: install_libyaml.yml
  when: ansible_distribution == 'Rocky'

- name: Install asdf plugins and set versions for each user
  ansible.builtin.include_tasks: package_individual_setup.yml
  loop: "{{ enriched_asdf_enriched_users }}"
  when: item.username != 'root'
