---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ asdf_os_family }}.yml"

- name: Include OS-Specific tasks
  ansible.builtin.include_tasks: "setup-{{ asdf_os_family }}.yml"

- name: Clone asdf
  ansible.builtin.git:
    repo: "{{ asdf_git_repo }}"
    dest: "{{ asdf_dest_folder }}"
    clone: yes
    update: no

- name: Check and Download necessary files
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/check-and-download.yml"
  loop:
    - name: setup_asdf.sh
      path: "{{ asdf_setup_script }}"
      url: "{{ asdf_setup_script_url }}"
    - name: .tool-versions
      path: "{{ asdf_tool_versions }}"
      url: "{{ asdf_tool_versions_url }}"
  loop_control:
    loop_var: item

- name: Check if setup is already done
  ansible.builtin.stat:
    path: "{{ asdf_setup_script }}"
  register: setup_check

- name: Execute setup_asdf.sh
  ansible.builtin.script:
    cmd: "{{ asdf_setup_script }} {{ asdf_languages }}"
    remote_src: true
  args:
    executable: "{{ ansible_user_shell }}"
  when:
    - ansible_user_shell is search('/bash') or ansible_user_shell is search('/zsh')
    - not setup_check.stat.exists # Only execute if setup is not done
