---
- name: Set default username for Kali systems
  ansible.builtin.set_fact:
    asdf_default_username: "kali"
  when: ansible_distribution_release == "kali-rolling"

- name: Clone asdf for each user
  ansible.builtin.git:
    repo: "{{ asdf_git_repo }}"
    dest: "/home/{{ item.username }}/.asdf"
    clone: true
    update: false
  loop: "{{ asdf_users }}"
  loop_control:
    loop_var: item
  when:
    - asdf_users is defined
    - item.username != 'root'

- name: Check and download necessary files for each user
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/check_and_download.yml"
  loop: "{{ asdf_users }}"
  loop_control:
    loop_var: asdf_user

- name: Iterate over users for setting up scripts
  ansible.builtin.include_tasks: setup_scripts.yml
  loop: "{{ asdf_users }}"
  loop_control:
    loop_var: asdf_user

- name: Update shell profiles for each user
  ansible.builtin.lineinfile:
    path: "/home/{{ user_line.0.username }}/{{ (ansible_user_shell == '/bin/zsh') | ternary('.zshrc', '.bashrc') }}"
    line: "{{ user_line.1 }}"
    state: present
  loop: "{{ asdf_users | subelements('shell_profile_lines') }}"
  loop_control:
    loop_var: user_line
  when: user_line.0.username != 'root'
