---
- name: Set default username for Kali systems
  ansible.builtin.set_fact:
    asdf_username: "kali"
  when: ansible_distribution_release == "kali-rolling" and asdf_username is not defined

- name: Reapply external asdf_plugins variable if provided
  ansible.builtin.set_fact:
    asdf_plugins: "{{ hostvars[inventory_hostname]['asdf_plugins'] | default(asdf_plugins) }}"
  when: hostvars[inventory_hostname]['asdf_plugins'] is defined

- name: Check available shells
  ansible.builtin.stat:
    path: "{{ item }}"
  register: shell_check
  with_items: "{{ asdf_shells }}"
  changed_when: false

- name: Set available shell fact
  ansible.builtin.set_fact:
    available_shell: "{{ (shell_check.results | selectattr('stat.exists', 'true') | list | first).item | default('/bin/sh') }}"

- name: Fetch ASDF MD5 checksum
  ansible.builtin.get_url:
    url: "{{ asdf_checksum_url }}"
    dest: "/tmp/asdf-{{ asdf_version }}-{{ asdf_os }}-{{ asdf_arch }}.tar.gz.md5"
    mode: "0644"

- name: Extract ASDF MD5 checksum
  ansible.builtin.command: "cat /tmp/asdf-{{ asdf_version }}-{{ asdf_os }}-{{ asdf_arch }}.tar.gz.md5"
  register: asdf_checksum
  changed_when: false

- name: Download ASDF binary
  ansible.builtin.get_url:
    url: "{{ asdf_download_url }}"
    dest: "/tmp/asdf-{{ asdf_version }}.tar.gz"
    checksum: "md5:{{ asdf_checksum.stdout | trim }}"
    mode: "0644"

- name: Ensure .asdf directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.asdf"
    state: directory
    owner: "{{ asdf_username }}"
    group: "{{ asdf_usergroup }}"
    mode: "0755"
  become: "{{ ansible_facts['os_family'] != 'Darwin' }}"

- name: Extract ASDF binary
  ansible.builtin.unarchive:
    src: "/tmp/asdf-{{ asdf_version }}.tar.gz"
    dest: "{{ ansible_env.HOME }}/.asdf"
    remote_src: true
    extra_opts: [ "--strip-components=1" ]
    owner: "{{ asdf_username }}"
    group: "{{ asdf_username }}"
    mode: "0755"
  become: true

- name: Update shell profile for ASDF
  ansible.builtin.include_tasks: update_shell_profile.yml
  vars:
    asdf_enriched_user:
      username: "{{ asdf_username }}"
      usergroup: "{{ asdf_usergroup }}"
      home: "{{ ansible_env.HOME }}"
      shell: "{{ available_shell }}"
      shell_profile_lines:
        - "# ASDF Setup"
        - "export ASDF_DIR=$HOME/.asdf"
        - ". \"$HOME/.asdf/asdf.sh\""
        - ". \"$HOME/.asdf/completions/asdf.bash\""

- name: Ensure ASDF bin directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.asdf/bin"
    state: directory
    owner: "{{ asdf_username }}"
    group: "{{ asdf_username }}"
    mode: "0755"
  become: "{{ ansible_facts['os_family'] != 'Darwin' }}"

- name: Download asdf.sh file
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/asdf-vm/asdf/master/asdf.sh"
    dest: "{{ ansible_env.HOME }}/.asdf/asdf.sh"
    mode: "0644"
    owner: "{{ asdf_username }}"
    group: "{{ asdf_username }}"
  become: true

- name: Copy asdf script to bin directory
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.asdf/asdf.sh"
    dest: "{{ ansible_env.HOME }}/.asdf/bin/asdf"
    remote_src: yes
    mode: "0755"
    owner: "{{ asdf_username }}"
    group: "{{ asdf_username }}"
  become: true

- name: Deploy .tool-versions file
  ansible.builtin.template:
    src: tool-versions.j2
    dest: "{{ ansible_env.HOME }}/.tool-versions"
    owner: "{{ asdf_username }}"
    group: "{{ asdf_usergroup }}"
    mode: "0644"
  become: "{{ ansible_facts['os_family'] != 'Darwin' }}"

- name: Ensure proper ownership of ASDF directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.asdf"
    state: directory
    owner: "{{ asdf_username }}"
    group: "{{ asdf_username }}"
    recurse: true
  become: true

- name: Install libyaml from source
  ansible.builtin.include_tasks: install_libyaml.yml
  when: ansible_distribution == 'Rocky'

- name: Initialize plugins with versions
  ansible.builtin.set_fact:
    asdf_plugins_with_versions: []

- name: Get available versions for plugins
  ansible.builtin.include_tasks: tasks/get_available_versions.yml
  loop: "{{ asdf_plugins }}"
  loop_control:
    loop_var: plugin
  register: plugin_versions

- name: Update plugins with available versions
  ansible.builtin.set_fact:
    "{{ asdf_plugins_with_versions + [plugin | combine({'version': available_versions.stdout_lines[-1] | default('latest')})] }}"
  loop: "{{ asdf_plugins }}"
  loop_control:
    loop_var: plugin
  vars:
    available_versions: "{{ (plugin_versions.results | selectattr('item.name', 'equalto', plugin.name) | list)[0].available_version }}"

- name: Deploy ASDF plugin installation script
  ansible.builtin.template:
    src: templates/install_asdf_plugins.sh.j2
    dest: /tmp/install_asdf_plugins.sh
    mode: '0755'
  changed_when: false

- name: Run ASDF plugin installation script
  ansible.builtin.shell: /tmp/install_asdf_plugins.sh
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
    PATH: "{{ ansible_env.HOME }}/.asdf/bin:{{ ansible_env.HOME }}/.asdf/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    ASDF_BIN: "{{ ansible_env.HOME }}/.asdf/bin/asdf"
    ASDF_DIR: "{{ ansible_env.HOME }}/.asdf"
  become: true
  become_user: "{{ asdf_username }}"
  changed_when: false
  failed_when: asdf_result.rc != 0
