---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ asdf_os_family }}.yml"

- name: Include OS-Specific tasks
  ansible.builtin.include_tasks: "setup-{{ asdf_os_family }}.yml"

- name: Clone asdf
  ansible.builtin.git:
    repo: "{{ asdf_git_repo }}"
    dest: "{{ asdf_dest_folder }}"
    clone: yes
    update: no

- name: Check and Download necessary files
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/check-and-download.yml"
  loop:
    - name: setup_asdf.sh
      path: "{{ asdf_setup_script }}"
      url: "{{ asdf_setup_script_url }}"
    - name: .tool-versions
      path: "{{ asdf_tool_versions }}"
      url: "{{ asdf_tool_versions_url }}"
  loop_control:
    loop_var: item

- name: Check if asdf_setup_script exists
  ansible.builtin.stat:
    path: "{{ asdf_setup_script }}"

- name: Check if necessary items exist
  ansible.builtin.stat:
    path: "{{ item.path }}"
  loop:
    - name: .asdf directory
      path: "{{ ansible_env.HOME }}/.asdf"
    - name: .tool-versions file
      path: "{{ ansible_env.HOME }}/.tool-versions"
    - name: ruby plugin directory
      path: "{{ ansible_env.HOME }}/.asdf/plugins/ruby"
  loop_control:
    loop_var: item
  register: check_results

- name: Ensure setup_asdf.sh is executable
  ansible.builtin.file:
    path: "{{ asdf_setup_script }}"
    mode: "0755"

- name: Execute setup_asdf.sh
  ansible.builtin.shell:
    cmd: "{{ asdf_setup_script }} {{ asdf_languages }}"
  args:
    executable: "{{ ansible_user_shell }}"
  when: >
    ansible_user_shell is search('/bash') or ansible_user_shell is search('/zsh') and
    (check_results.results | selectattr('stat.exists', 'equalto', false) | list | length > 0)
  changed_when: false

- name: Update shell profile with ASDF_PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/{{ (ansible_user_shell == '/bin/zsh') | ternary('.zshrc', '.bashrc') }}"
    line: 'ASDF_PATH="{{ ansible_env.HOME }}/.asdf"'
    state: present

- name: Update shell profile with updated PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/{{ (ansible_user_shell == '/bin/zsh') | ternary('.zshrc', '.bashrc') }}"
    line: "export PATH=$PATH:$ASDF_PATH"
    state: present

- name: Update shell profile with ASDF source command
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/{{ (ansible_user_shell == '/bin/zsh') | ternary('.zshrc', '.bashrc') }}"
    line: '. "{{ ansible_env.HOME }}/.asdf/asdf.sh"'
    state: present
  changed_when: false

- name: Reload shell to apply ASDF settings
  ansible.builtin.shell:
    cmd: "source {{ ansible_env.HOME }}/{{ (ansible_user_shell == '/bin/zsh') | ternary('.zshrc', '.bashrc') }}"
  when:
    - ansible_user_shell is search('/bash') or ansible_user_shell is search('/zsh')
  args:
    executable: "{{ ansible_user_shell }}"
  changed_when: false
