---
- name: Gather shell for the current user
  ansible.builtin.getent:
    database: passwd
    key: "{{ ansible_user_id }}"
  register: getent_user_shell_non_macos
  when:
    - ansible_os_family != 'Darwin'
    - asdf_global_install

- name: Set the current user's shell for non-macOS
  ansible.builtin.set_fact:
    user_shell: "{{ getent_user_shell_non_macos.ansible_facts.getent_passwd[ansible_user_id][6] if (getent_user_shell_non_macos.ansible_facts.getent_passwd[ansible_user_id] | length >= 7) else '/bin/sh' }}"
  when:
    - ansible_os_family != 'Darwin'
    - asdf_global_install

- name: Gather shell for the current user on macOS
  cowdogmoo.workstation.getent_passwd:
  register: getent_user_shell_macos
  when:
    - ansible_os_family == 'Darwin'
    - asdf_global_install

- name: Set the current user's shell for macOS
  ansible.builtin.set_fact:
    user_shell: "{{ getent_user_shell_macos.getent_passwd[ansible_user_id][5] }}"
  when:
    - ansible_os_family == 'Darwin'
    - asdf_global_install

- name: Debug getent_user_shell
  ansible.builtin.debug:
    var: getent_user_shell
  when: asdf_global_install

- name: Find Bash executable
  ansible.builtin.command:
    cmd: "which bash"
  register: bash_path
  changed_when: false
  when: asdf_global_install

- name: Install asdf plugins globally
  become: true
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      . /etc/profile.d/asdf.sh
      {% for user in asdf_users %}
        {% for plugin in user.plugins %}
          plugins=$(asdf plugin list)
          grep -q "{{ plugin.name }}" <<< "$plugins" || asdf plugin add "{{ plugin.name }}"
          asdf install "{{ plugin.name }}" "{{ plugin.version }}"
          asdf global "{{ plugin.name }}" "{{ plugin.version }}"
        {% endfor %}
      {% endfor %}
    executable: "{{ bash_path.stdout }}"
  changed_when: false
  when: asdf_global_install

- name: Install asdf plugins for each user
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      . "{{ asdf_install_script_path }}" "{{ asdf_user.home }}"
      {% if asdf_user.plugins is defined %}
      {% for plugin in asdf_user.plugins %}
      plugins=$(asdf plugin list)
      grep -q "{{ plugin.name }}" <<< "$plugins" || asdf plugin add "{{ plugin.name }}"
      asdf install "{{ plugin.name }}" "{{ plugin.version }}"
      if [ "{{ plugin.scope }}" = "global" ]; then
        asdf global "{{ plugin.name }}" "{{ plugin.version }}"
      elif [ "{{ plugin.scope }}" = "local" ]; then
        asdf local "{{ plugin.name }}" "{{ plugin.version }}"
      else
        echo "Invalid scope: {{ plugin.scope }}"
        exit 1
      fi
      {% endfor %}
      {% endif %}
    executable: "{{ asdf_user.shell }}"
  loop: "{{ asdf_enriched_users }}"
  loop_control:
    loop_var: asdf_user
    label: "{{ asdf_user.username }}"
  become: true
  become_user: "{{ asdf_user.username }}"
  changed_when: false
  when: not asdf_global_install
