---
- name: Get all plugins for each user
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      . {{ asdf_install_script_path }} "{{ item.home_path }}"
      asdf plugin list
    executable: "{{ item.shell }}"
  register: asdf_plugins
  changed_when: false
  become: true
  become_user: "{{ item.username }}"

- name: Install asdf plugins for each user
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      . "{{ asdf_install_script_path }}" "{{ item.home_path }}"
      {% for plugin in item.plugins %}
      if ! asdf plugin list | grep -q "{{ plugin.name }}"; then
        asdf plugin add "{{ plugin.name }}"
      fi
      {% endfor %}
    executable: "{{ item.shell }}"
  become: true
  become_user: "{{ item.username }}"
  changed_when: false

- name: Install specific version of asdf plugins for each user
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      . "{{ asdf_install_script_path }}" "{{ item.home_path }}"
      {% for plugin in item.plugins %}
      asdf install "{{ plugin.name }}" "{{ plugin.version }}"
      if [ "{{ plugin.scope }}" = "global" ]; then
        asdf global "{{ plugin.name }}" "{{ plugin.version }}"
      elif [ "{{ plugin.scope }}" = "local" ]; then
        asdf local "{{ plugin.name }}" "{{ plugin.version }}"
      else
        echo "Invalid scope: {{ plugin.scope }}"
        exit 1
      fi
      {% endfor %}
    executable: "{{ item.shell }}"
  become: true
  become_user: "{{ item.username }}"
  changed_when: false
