---
- name: "Install asdf plugin for {{ package.name }}"
  ansible.builtin.shell:
    cmd: "export ASDF_DIR=/home/{{ username }}/.asdf && . /home/{{ username }}/.asdf/asdf.sh && asdf plugin add {{ package.name }}"
  become: true
  become_user: "{{ username }}"

- name: "Install {{ package.name }} version {{ package.version }}"
  ansible.builtin.shell:
    cmd: "export ASDF_DIR=/home/{{ username }}/.asdf && . /home/{{ username }}/.asdf/asdf.sh && asdf install {{ package.name }} {{ package.version }}"
  become: true
  become_user: "{{ username }}"

- name: "Set {{ package.name }} version {{ package.version }} {{ package.scope }}"
  ansible.builtin.shell:
    cmd: "export ASDF_DIR=/home/{{ username }}/.asdf && . /home/{{ username }}/.asdf/asdf.sh && asdf {{ package.scope }} {{ package.name }} {{ package.version }}"
  become: true
  become_user: "{{ username }}"
