---
- name: Ensure .tool-versions file is present for each user
  ansible.builtin.get_url:
    url: "{{ script.url }}"
    dest: "{{ script.path }}"
    mode: "0644"
  loop: "{{ asdf_user.asdf_setup_scripts }}"
  loop_control:
    loop_var: script
  when: script.name == '.tool-versions'
