---
- name: Check if shell exists
  ansible.builtin.command: "which {{ user.shell | default('/bin/bash') }}"
  register: shell_path
  ignore_errors: true
  changed_when: false

- name: Update shell profile for users
  ansible.builtin.blockinfile:
    path: "{{ enriched_user.home }}/{{ (shell_path.stdout == '') | ternary('.bashrc', (enriched_user.shell == '/bin/zsh') | ternary('.zshrc', '.bashrc')) }}"
    block: |
      {% for line in enriched_user.shell_profile_lines %}
      {{ line }}
      {% endfor %}
    create: true
    mode: "0644"
  become: true
  become_user: "{{ enriched_user.username }}"
  loop: "{{ asdf_enriched_users }}"
  loop_control:
    loop_var: enriched_user
  when: shell_path.stdout != ""

- name: Ensure user home directory exists
  ansible.builtin.include_tasks: ensure_directory_exists.yml
  vars:
    directories:
      - path: "{{ enriched_user.home }}"
        owner: "{{ enriched_user.username }}"
        group: "{{ enriched_user.usergroup | default(enriched_user.username) }}"
        mode: '0755'
  loop: "{{ asdf_enriched_users }}"
  loop_control:
    loop_var: enriched_user
  when:
    - enriched_user.username in ansible_facts.getent_passwd
