---
- name: Check if shell exists
  ansible.builtin.command: "which {{ asdf_enriched_user.shell | default('/bin/bash') }}"
  register: shell_path
  ignore_errors: true
  changed_when: false

- name: Set detected shell fact
  ansible.builtin.set_fact:
    detected_shell: "{{ shell_path.stdout if shell_path.stdout != '' else '/bin/bash' }}"

- name: Update asdf_enriched_user with detected shell
  ansible.builtin.set_fact:
    asdf_enriched_user: "{{ asdf_enriched_user | combine({'shell': detected_shell}) }}"

- name: Set ASDF profile lines
  ansible.builtin.set_fact:
    asdf_profile_lines:
      - "# ASDF Setup"
      - "export ASDF_DIR=$HOME/.asdf"
      - "export ASDF_DATA_DIR=$HOME/.asdf"
      - ". \"$HOME/.asdf/asdf.sh\""
      - ". \"$HOME/.asdf/completions/asdf.bash\""

- name: Update shell profile for the user
  ansible.builtin.blockinfile:
    path: "{{ asdf_enriched_user.home }}/{{ (detected_shell == '/bin/zsh') | ternary('.zshrc', '.bashrc') }}"
    block: |
      {% for line in asdf_profile_lines %}
      {{ line }}
      {% endfor %}
    create: true
    mode: "0644"
  become: true
  become_user: "{{ asdf_enriched_user.username }}"

- name: Ensure user home directory exists (via include)
  ansible.builtin.include_tasks: ensure_directory_exists.yml
  args:
    apply:
      become: "{{ ansible_facts['os_family'] != 'Darwin' }}"
  vars:
    directories:
      - path: "{{ asdf_enriched_user.home }}"
        owner: "{{ asdf_enriched_user.username }}"
        group: "{{ asdf_enriched_user.usergroup | default(asdf_enriched_user.username) }}"
        mode: "0755"
