---
- name: Check if shell exists
  ansible.builtin.command: "which {{ user.shell | default('/bin/bash') }}"
  register: shell_path
  ignore_errors: true
  changed_when: false

- name: Update shell profile for user
  ansible.builtin.lineinfile:
    path: "{{ user.home }}/{{ (shell_path.stdout == '') | ternary('.bashrc', (user.shell == '/bin/zsh') | ternary('.zshrc', '.bashrc')) }}"
    line: "{{ item }}"
    insertafter: EOF
    create: true
    mode: "0644"
  become: true
  become_user: "{{ user.username }}"
  loop: "{{ line }}"
  when: shell_path.stdout != ""
