---
- name: Check if shell exists
  ansible.builtin.command: "which {{ user.shell | default('/bin/bash') }}"
  register: shell_path
  ignore_errors: true
  changed_when: false

- name: Update shell profile for users
  ansible.builtin.blockinfile:
    path: "{{ user.home }}/{{ (shell_path.stdout == '') | ternary('.bashrc', (user.shell == '/bin/zsh') | ternary('.zshrc', '.bashrc')) }}"
    block: |
      {% for line in user.shell_profile_lines %}
      {{ line }}
      {% endfor %}
    create: true
    mode: "0644"
  become: true
  become_user: "{{ user.username }}"
  loop: "{{ asdf_enriched_users }}"
  loop_control:
    loop_var: user
  when: shell_path.stdout != ""
