---
- name: Check if shell exists
  ansible.builtin.command: "which {{ user.shell | default('/bin/bash') }}"
  register: shell_path
  ignore_errors: true
  changed_when: false

- name: Set detected shell fact
  ansible.builtin.set_fact:
    detected_shell: "{{ shell_path.stdout if shell_path.stdout != '' else '/bin/bash' }}"

- name: Update asdf_enriched_users with detected shell
  ansible.builtin.set_fact:
    asdf_enriched_users: >-
      {{ asdf_enriched_users | map('combine', {'shell': detected_shell}) | list }}

- name: Update shell profile for users
  ansible.builtin.blockinfile:
    path: "{{ enriched_user.home }}/{{ (detected_shell == '/bin/zsh') | ternary('.zshrc', '.bashrc') }}"
    block: |
      {% for line in enriched_user.shell_profile_lines %}
      {{ line }}
      {% endfor %}
    create: true
    mode: "0644"
  become: true
  become_user: "{{ enriched_user.username }}"
  loop: "{{ asdf_enriched_users }}"
  loop_control:
    loop_var: enriched_user

- name: Ensure user home directory exists
  ansible.builtin.include_tasks: ensure_directory_exists.yml
  args:
    apply:
      become: "{{ ansible_facts['os_family'] != 'Darwin' }}"
  vars:
    directories:
      - path: "{{ enriched_user.home }}"
        owner: "{{ enriched_user.username }}"
        group: "{{ enriched_user.usergroup | default(enriched_user.username) }}"
        mode: '0755'
  loop: "{{ asdf_enriched_users }}"
  loop_control:
    loop_var: enriched_user
  when:
    - enriched_user.username in ansible_facts.getent_passwd
