---
- name: Get home directory for each user
  ansible.builtin.shell: "eval echo ~{{ item.username }}"
  loop: "{{ zsh_setup_users }}"
  register: home_dirs
  become: true
  become_user: "{{ item.username }}"
  changed_when: false

- name: Update home_path for each user in zsh_setup_users
  ansible.builtin.set_fact:
    enriched_setup_users: "{{ enriched_setup_users | default([]) + [item.0 | combine({'home_path': item.1.stdout})] }}"
  loop: "{{ zsh_setup_users | zip(home_dirs.results) }}"
