---
- name: Include get_enriched_users tasks
  ansible.builtin.include_tasks: get_enriched_users.yml

- name: Check if .oh-my-zsh exists for all zsh_setup_users
  ansible.builtin.stat:
    path: "{{ item.home_path }}/.oh-my-zsh"
  register: oh_my_zsh_installed
  loop: "{{ enriched_setup_users }}"

- name: Download oh-my-zsh install script for all zsh_setup_users
  ansible.builtin.get_url:
    url: "{{ zsh_setup_omz_install_script_url }}"
    dest: "{{ item.home_path }}/omz-installer.sh"
    mode: "0755"
    owner: "{{ item.username }}"
    group: "{{ item.usergroup }}"
  become: true
  become_user: "{{ item.username }}"
  when: "not oh_my_zsh_installed.results[item | int].stat.exists"
  loop: "{{ enriched_setup_users }}"
  changed_when: false

- name: Install oh-my-zsh for all zsh_setup_users
  ansible.builtin.shell: "echo 'y' | {{ item.home_path }}/omz-installer.sh --unattended --keep-zshrc" # noqa risky-shell-pipe
  args:
    creates: "{{ item.home_path }}/.oh-my-zsh"
  become: true
  become_user: "{{ item.username }}"
  when: "not oh_my_zsh_installed.results[item | int].stat.exists"
  loop: "{{ enriched_setup_users }}"
  changed_when: false

- name: Remove omz-installer.sh for all zsh_setup_users
  ansible.builtin.file:
    path: "{{ item.home_path }}/omz-installer.sh"
    state: absent
  become: true
  become_user: "{{ item.username }}"
  loop: "{{ enriched_setup_users }}"

- name: Check if .zshrc exists for all zsh_setup_users
  ansible.builtin.stat:
    path: "{{ item.home_path }}/.zshrc"
  register: zshrc_exists
  loop_control:
    index_var: loop_index
  become: true
  become_user: "{{ item.username }}"
  loop: "{{ enriched_setup_users }}"

- name: Copy .zshrc template to user's home directory if it does not exist
  ansible.builtin.template:
    src: zshrc.j2
    mode: "0755"
    dest: "{{ item.home_path }}/.zshrc"
    owner: "{{ item.username }}"
    group: "{{ item.usergroup | default(item.username) }}"
  loop: "{{ enriched_setup_users }}"
  loop_control:
    index_var: loop_index
  become: true
  become_user: "{{ item.username }}"
  when: "not zshrc_exists.results[loop_index].stat.exists"
