---
- name: Check if .oh-my-zsh exists for all zsh_setup_users
  ansible.builtin.stat:
    path: "{{ (ansible_system == 'Darwin') | ternary('/Users', '/home') }}/{{ item.username }}/.oh-my-zsh"
  register: oh_my_zsh_installed
  with_items: "{{ zsh_setup_users }}"

- name: Download oh-my-zsh install script for all zsh_setup_users
  ansible.builtin.get_url:
    url: "https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh"
    dest: "{{ (item.username == 'root') | ternary('/root', (ansible_system == 'Darwin' and item.username != 'root') | ternary('/Users', '/home') + '/' + item.username) }}/zsh-installer.sh"
    mode: "0755"
    owner: "{{ item.username }}"
    group: "{{ item.usergroup | default(item.username) }}"
  when: "not oh_my_zsh_installed.results[item | int].stat.exists"
  with_items: "{{ zsh_setup_users }}"
  changed_when: false

- name: Install oh-my-zsh for all zsh_setup_users
  ansible.builtin.command: "echo 'y' | ZSH={{ (ansible_system == 'Darwin' and item.username != 'root') | ternary('/Users', '/home') }}/{{ item.username }}/.oh-my-zsh bash {{ (ansible_system == 'Darwin' and item.username != 'root') | ternary('/Users', '/home') }}/{{ item.username }}/zsh-installer.sh"
  args:
    creates: "{{ (ansible_system == 'Darwin' and item.username != 'root') | ternary('/Users', '/home') }}/{{ item.username }}/.oh-my-zsh"
  become: true
  become_user: "{{ item.username }}"
  when: "not oh_my_zsh_installed.results[item | int].stat.exists and ansible_system != 'Darwin'"
  with_items: "{{ zsh_setup_users }}"
  changed_when: false

- name: Check if zsh-installer.sh exists for all zsh_setup_users
  ansible.builtin.stat:
    path: "/home/{{ item.username }}/zsh-installer.sh"
  register: zsh_installer_exists
  with_items: "{{ zsh_setup_users }}"

- name: Ensure zsh-installer.sh is executable for all zsh_setup_users
  ansible.builtin.file:
    path: "{{ (item.username == 'root') | ternary('/root', (ansible_system == 'Darwin' and item.username != 'root') | ternary('/Users', '/home') + '/' + item.username) }}/zsh-installer.sh"
    mode: "0755"
  become: true
  become_user: "{{ item.username }}"
  when: "zsh_installer_exists.results[item | int].stat.exists"
  with_items: "{{ zsh_setup_users }}"
  changed_when: false

- name: Execute zsh-installer.sh for all zsh_setup_users
  ansible.builtin.shell:
    cmd: "bash {{ (item.username == 'root') | ternary('/root', '/home/' + item.username) }}/zsh-installer.sh"
  args:
    executable: "/bin/bash"
  become: true
  become_user: "{{ item.username }}"
  when: "zsh_installer_exists.results[item | int].stat.exists"
  with_items: "{{ zsh_setup_users }}"
  changed_when: false

- name: Remove zsh-installer.sh for all zsh_setup_users
  ansible.builtin.file:
    path: "{{ (ansible_system == 'Darwin' and item.username != 'root') | ternary('/Users', '/home') }}/{{ item.username }}/zsh-installer.sh"
    state: absent
  become: true
  become_user: "{{ item.username }}"
  when: "zsh_installer_exists.results[item | int].stat.exists"
  with_items: "{{ zsh_setup_users }}"
  changed_when: false

- name: Create per-user $HOME/.zshrc files if they do not exist
  ansible.builtin.stat:
    path: "{{ (item.username == 'root') | ternary('/root', (ansible_system == 'Darwin' and item.username != 'root') | ternary('/Users', '/home') + '/' + item.username) }}/.zshrc"
  register: zshrc_exists
  loop: "{{ zsh_setup_users }}"

- name: Copy .zshrc template to user's home directory if it does not exist
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ (item.0.username == 'root') | ternary('/root', (ansible_system == 'Darwin' and item.0.username != 'root') | ternary('/Users', '/home') + '/' + item.0.username) }}/.zshrc"
    mode: "0755"
    owner: "{{ item.0.username }}"
    group: "{{ item.0.usergroup | default(item.0.username) }}"
  loop: "{{ zshrc_exists.results | zip(zsh_setup_users) }}"
  when: not item.0.stat.exists
