---
- name: Include zsh_setup_get_enriched_users tasks
  ansible.builtin.include_tasks: zsh_setup_get_enriched_users.yml

- name: Check if .oh-my-zsh exists for each user
  ansible.builtin.stat:
    path: "{{ item.home }}/.oh-my-zsh"
  register: oh_my_zsh_installed
  loop: "{{ zsh_setup_enriched_users | flatten }}"

- name: Download oh-my-zsh install script for all zsh_setup_enriched_users
  ansible.builtin.get_url:
    url: "{{ zsh_setup_omz_install_script_url }}"
    dest: "{{ item.home }}/omz-installer.sh"
    mode: "0755"
    owner: "{{ item.username }}"
    group: "{{ item.usergroup }}"
  become: true
  become_user: "{{ item.username }}"
  when:
    - item.home is defined
    - item.home | length > 0
  loop: "{{ zsh_setup_enriched_users }}"
  changed_when: false

- name: Install oh-my-zsh for all zsh_setup_enriched_users
  ansible.builtin.shell: |
    set -o pipefail
    echo 'y' | {{ item.home }}/omz-installer.sh --unattended --keep-zshrc
  args:
    creates: "{{ item.home }}/.oh-my-zsh"
    executable: /bin/zsh
  become: true
  become_user: "{{ item.username }}"
  when: "not oh_my_zsh_installed.results[item | int].stat.exists"
  loop: "{{ zsh_setup_enriched_users }}"
  changed_when: false

- name: Check if omz-installer.sh exists for each user
  ansible.builtin.stat:
    path: "{{ item.home }}/omz-installer.sh"
  register: omz_installer_exists
  loop: "{{ zsh_setup_enriched_users }}"

- name: Remove omz-installer.sh for all zsh_setup_enriched_users
  ansible.builtin.file:
    path: "{{ item.home }}/omz-installer.sh"
    state: absent
  become: true
  become_user: "{{ item.username }}"
  when: omz_installer_exists.results[item | int].stat.exists
  loop: "{{ zsh_setup_enriched_users }}"
  changed_when: false

- name: Check if .zshrc exists for all zsh_setup_enriched_users
  ansible.builtin.stat:
    path: "{{ item.home }}/.zshrc"
  register: zshrc_exists
  loop: "{{ zsh_setup_enriched_users }}"

- name: Copy .zshrc template to user's home directory if it does not exist
  ansible.builtin.template:
    src: zshrc.j2
    mode: "0644"
    dest: "{{ item.home }}/.zshrc"
    owner: "{{ item.username }}"
    group: "{{ item.usergroup | default(item.username) }}"
  loop: "{{ zsh_setup_enriched_users }}"
  loop_control:
    index_var: loop_index
  become: true
  become_user: "{{ item.username }}"
  when: not zshrc_exists.results[loop_index].stat.exists
