---
- name: Include zsh_setup_get_enriched_users tasks
  ansible.builtin.include_tasks: zsh_setup_get_enriched_users.yml

- name: Ensure groups exist for users
  ansible.builtin.group:
    name: "{{ user.usergroup }}"
    state: present
  loop: "{{ zsh_setup_enriched_users }}"
  loop_control:
    loop_var: user

- name: Ensure user exists
  ansible.builtin.user:
    name: "{{ user.username }}"
    group: "{{ user.usergroup }}"
    shell: "{{ user.shell }}"
    home: "{{ user.home }}"
    state: present
  loop: "{{ zsh_setup_enriched_users }}"
  loop_control:
    loop_var: user

- name: Ensure user home directory exists
  ansible.builtin.file:
    path: "{{ user.home }}"
    state: directory
    owner: "{{ user.username }}"
    group: "{{ user.usergroup | default(user.username) }}"
    mode: "0755"
  loop: "{{ zsh_setup_enriched_users }}"
  loop_control:
    loop_var: user
  when: user.home is defined

- name: Check if .oh-my-zsh exists for each user
  ansible.builtin.stat:
    path: "{{ user.home }}/.oh-my-zsh"
  register: oh_my_zsh_installed
  loop: "{{ zsh_setup_enriched_users | flatten }}"
  loop_control:
    loop_var: user

- name: Download oh-my-zsh install script for all zsh_setup_enriched_users
  ansible.builtin.get_url:
    url: "{{ zsh_setup_omz_install_script_url }}"
    dest: "{{ user.home }}/omz-installer.sh"
    mode: "0755"
    owner: "{{ user.username }}"
    group: "{{ user.usergroup }}"
  become: true
  when:
    - user.home is defined
    - user.home | length > 0
  loop: "{{ zsh_setup_enriched_users }}"
  loop_control:
    loop_var: user
  changed_when: false

- name: Install oh-my-zsh for all zsh_setup_enriched_users
  ansible.builtin.shell: |
    set -o pipefail
    echo 'y' | {{ user.home }}/omz-installer.sh --unattended --keep-zshrc
  args:
    creates: "{{ user.home }}/.oh-my-zsh"
    executable: /bin/zsh
  become: true
  become_user: "{{ user.username }}"
  when: "not oh_my_zsh_installed.results[user | int].stat.exists"
  loop: "{{ zsh_setup_enriched_users }}"
  loop_control:
    loop_var: user
  changed_when: false

- name: Check if omz-installer.sh exists for each user
  ansible.builtin.stat:
    path: "{{ user.home }}/omz-installer.sh"
  register: omz_installer_exists
  loop: "{{ zsh_setup_enriched_users }}"
  loop_control:
    loop_var: user

- name: Remove omz-installer.sh for all zsh_setup_enriched_users
  ansible.builtin.file:
    path: "{{ user.home }}/omz-installer.sh"
    state: absent
  become: true
  become_user: "{{ user.username }}"
  when: omz_installer_exists.results[user | int].stat.exists
  loop: "{{ zsh_setup_enriched_users }}"
  loop_control:
    loop_var: user
  changed_when: false

- name: Check if .zshrc exists for all zsh_setup_enriched_users
  ansible.builtin.stat:
    path: "{{ user.home }}/.zshrc"
  register: zshrc_exists
  loop: "{{ zsh_setup_enriched_users }}"
  loop_control:
    loop_var: user

- name: Copy .zshrc template to user's home directory if it does not exist
  ansible.builtin.template:
    src: zshrc.j2
    mode: "0644"
    dest: "{{ user.home }}/.zshrc"
    owner: "{{ user.username }}"
    group: "{{ user.usergroup | default(user.username) }}"
  loop: "{{ zsh_setup_enriched_users }}"
  loop_control:
    index_var: loop_index
    loop_var: user
  become: true
  become_user: "{{ user.username }}"
  when: not zshrc_exists.results[loop_index].stat.exists
