- name: Ensure users exist and have home directories
  ansible.builtin.user:
    name: "{{ item.username }}"
    group: "{{ item.usergroup }}"
    shell: "{{ item.shell }}"
    create_home: true
    home: "{{ '/Users' if ansible_os_family == 'Darwin' else '/home' }}/{{ item.username }}"
  register: user_info
  loop: "{{ zsh_setup_users }}"
  loop_control:
    label: "{{ item.username }}"
  tags: user-setup

- name: Update home for all users
  ansible.builtin.set_fact:
    zsh_setup_enriched_users: >-
      {{ (zsh_setup_enriched_users | default([])) |
      rejectattr('username', 'equalto', item.username) | list +
      [item | combine({
        'home': item.home,
        })] | selectattr('home', 'defined') | list }}
  loop: "{{ user_info.results }}"
