---
- name: Get home directory for each user
  ansible.builtin.shell: >
    set -o pipefail
    getent passwd {{ item.username }} | cut -d: -f6
  register: home_dirs
  loop: "{{ zsh_setup_users }}"
  changed_when: false

- name: Update home_path for all users
  ansible.builtin.set_fact:
    zsh_setup_enriched_users: >-
      {{ (zsh_setup_enriched_users | default([])) | rejectattr('username', 'equalto', item.item.username) | list + [item.item | combine({
        'home_path': item.stdout,
        })] | selectattr('home_path', 'defined') | list }}
  loop: "{{ home_dirs.results }}"
  loop_control:
    label: "{{ item.item.username }}"
