---
- name: Get home directory for each user
  ansible.builtin.shell: >
    set -o pipefail
    getent passwd {{ item.username }} | cut -d: -f6
  args:
    executable: /bin/bash
  register: home_dirs
  loop: "{{ zsh_setup_users }}"
  changed_when: false

- name: Update home_path for all users
  ansible.builtin.set_fact:
    zsh_setup_enriched_users: >-
      {{ (zsh_setup_enriched_users | default([])) | rejectattr('username', 'equalto', item.0.username) | list + [item.0 | combine({
        'home_path': item.1.stdout,
        })] | selectattr('home_path', 'ne', '') | list }}
  loop: "{{ zsh_setup_users | zip(home_dirs.results) }}"
