---
- name: Update home for all users
  ansible.builtin.set_fact:
    zsh_setup_enriched_users: >-
      {{ (zsh_setup_enriched_users | default([])) |
      rejectattr('username', 'equalto', item.username) | list +
      [item | combine({
        'home': item.home,
        })] | selectattr('home', 'defined') | list }}
  loop: "{{ zsh_setup_users }}"
