---
- name: Install oh-my-zsh
  ansible.builtin.command: echo 'Y' | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  changed_when: false

- name: Create per-user $HOME/.zshrc files
  ansible.builtin.template:
    src: zshrc.j2
    dest: "/home/{{ item.username }}/.zshrc"
    mode: 0744
    owner: "{{ item.username }}"
    group: "{{ item.usergroup | default(item.username) }}"
  with_items: "{{ vnc_zsh_users }}"
