---
- name: Enable persistent services for all users
  ansible.builtin.shell: /bin/loginctl enable-linger {{ item.username }}
  changed_when: false
  with_items: "{{ vnc_users }}"

- name: Create systemd directories
  ansible.builtin.file:
    path: "{{ item.username == 'root' | ternary('/root', '/home/' + item.username) }}/.config/systemd/user"
    state: directory
    mode: 0744
    owner: "{{ item.username }}"
    group: "{{ item.usergroup | default(item.username) }}"
  with_items: "{{ vnc_users }}"

- name: Check existence of per-user systemd service files
  ansible.builtin.stat:
    path: "{{ item.username == 'root' | ternary('/root', '/home/' + item.username) }}/.config/systemd/user/vncserver@{{ item.vnc_num }}.service"
  with_items: "{{ vnc_users }}"

- name: Update per-user systemd service files
  ansible.builtin.template:
    src: vncserver.j2
    dest: "{{ item.username == 'root' | ternary('/root', '/home/' + item.username) }}/.config/systemd/user/vncserver@{{ item.vnc_num }}.service"
    mode: 0744
    owner: "{{ item.username }}"
    group: "{{ item.usergroup | default(item.username) }}"
  with_items: "{{ vnc_users }}"

- name: Check for service file presence
  ansible.builtin.stat:
    path: "{{ item.username == 'root' | ternary('/root', '/home/' + item.username) }}/.config/systemd/user/vncserver@{{ item.vnc_num }}.service"
  register: service_file_check
  with_items: "{{ vnc_users_uid.result }}"

- name: Report missing service files
  ansible.builtin.debug:
    msg: "Service file missing at {{ item.item.username == 'root' | ternary('/root', '/home/' + item.item.username) }}/.config/systemd/user/vncserver@{{ item.item.vnc_num }}.service"
  with_items: "{{ service_file_check.results }}"
  when: not item.stat.exists

- name: "Enable and start VNC service using command for {{ vnc_users_uid }}"
  ansible.builtin.shell: |
    systemctl --user enable --now vncserver@{{ item.vnc_num }}.service
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ item.uid }}"
  with_items: "{{ vnc_users_uid.result }}"
  become: false
