---
- name: Prepare
  hosts: all
  gather_facts: true
  vars:
    container_user: "{{ ansible_distribution | lower }}"
    container_home: "/home/{{ container_user }}"
  tasks:
    - name: Create test user
      ansible.builtin.user:
        name: "{{ container_user }}"
        shell: /bin/bash
        create_home: true
      become: true

    - name: Set home directory fact
      ansible.builtin.set_fact:
        ansible_env:
          HOME: "{{ container_home }}"
