---
- name: Check if already installed
  ansible.builtin.command: which claude
  register: claude_code_check
  changed_when: false
  failed_when: false

- name: Check if npm is available
  ansible.builtin.command: which npm
  register: claude_code_npm_check
  changed_when: false
  failed_when: false
  when: claude_code_check.rc != 0

- name: Install via npm
  community.general.npm:
    name: "@anthropic-ai/claude-code"
    global: true
    state: present
  become: true
  when:
    - claude_code_check.rc != 0
    - claude_code_npm_check.rc == 0

- name: Install via script (fallback)
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://claude.ai/install.sh | bash
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ claude_code_user_home }}"
  become: true
  become_user: "{{ claude_code_username }}"
  when:
    - claude_code_check.rc != 0
    - claude_code_npm_check.rc != 0
  register: claude_code_script_install
  changed_when: "'Successfully installed' in claude_code_script_install.stdout"

- name: Verify installation
  ansible.builtin.command: claude --version
  register: claude_code_version
  changed_when: false
  failed_when: false
  become: true
  become_user: "{{ claude_code_username }}"

- name: Display version
  ansible.builtin.debug:
    msg: "Claude Code installed: {{ claude_code_version.stdout }}"
  when: claude_code_version.rc == 0
