---
- name: Check if already installed
  ansible.builtin.command: which claude
  register: claude_code_check
  changed_when: false
  failed_when: false

- name: Install via Homebrew
  community.general.homebrew_cask:
    name: claude-code
    state: present
  when: claude_code_check.rc != 0

- name: Verify installation
  ansible.builtin.command: claude --version
  register: claude_code_version
  changed_when: false
  failed_when: false

- name: Display version
  ansible.builtin.debug:
    msg: "Claude Code installed: {{ claude_code_version.stdout }}"
  when: claude_code_version.rc == 0
