---
- name: Check if Claude Code is already installed (Windows)
  ansible.windows.win_command: where claude
  register: claude_code_windows_check
  changed_when: false
  failed_when: false

- name: Check if npm is available (Windows)
  ansible.windows.win_command: where npm
  register: claude_code_npm_check_windows
  changed_when: false
  failed_when: false
  when: claude_code_windows_check.rc != 0

- name: Install Claude Code via npm (Windows)
  ansible.windows.win_shell: npm install -g @anthropic-ai/claude-code
  when:
    - claude_code_windows_check.rc != 0
    - claude_code_npm_check_windows.rc == 0
  register: claude_code_npm_install
  changed_when: "'added' in claude_code_npm_install.stdout"

- name: Install Claude Code via PowerShell script (Windows - fallback)
  ansible.windows.win_shell: |
    irm https://claude.ai/install.ps1 | iex
  when:
    - claude_code_windows_check.rc != 0
    - claude_code_npm_check_windows.rc != 0
  register: claude_code_ps_install
  changed_when: "'Successfully installed' in claude_code_ps_install.stdout"

- name: Verify Claude Code installation (Windows)
  ansible.windows.win_command: claude --version
  register: claude_code_version_windows
  changed_when: false
  failed_when: false

- name: Display Claude Code version
  ansible.builtin.debug:
    msg: "Claude Code installed: {{ claude_code_version_windows.stdout }}"
  when: claude_code_version_windows.rc == 0
