---
# Languages to configure with asdf
asdf_languages:
  - golang
  - python
  - ruby

# Default username is the distribution name
asdf_default_username: "{{ ansible_distribution | lower }}"

# Users to setup with asdf, each with their specific setup scripts
asdf_users:
  - username: "{{ asdf_default_username }}"
    usergroup: "{{ asdf_default_username }}"
    asdf_setup_scripts:
      - name: setup_asdf.sh
        path: "/tmp/setup_asdf.sh"
        url: "https://raw.githubusercontent.com/l50/dotfiles/main/files/setup_asdf.sh"
      - name: .tool-versions
        path: "/home/{{ asdf_default_username }}/.tool-versions"
        url: "https://raw.githubusercontent.com/l50/dotfiles/main/.tool-versions"
    shell: "/usr/bin/zsh"
    shell_profile_lines:
      - 'export ASDF_PATH="/home/{{ asdf_default_username }}/.asdf"'
      - 'export PATH="$ASDF_PATH/bin:$ASDF_PATH/shims:$PATH"'
      - '. "/home/{{ asdf_default_username }}/.asdf/asdf.sh"'
