---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Include default variables
      ansible.builtin.include_vars:
        file: "../../defaults/main.yml"

    - name: Set OS family variable
      ansible.builtin.set_fact:
        asdf_os_family: "{{ ansible_facts['os_family'] | lower }}"

    - name: Include OS-specific variables
      ansible.builtin.include_vars:
        file: "../../vars/{{ asdf_os_family }}.yml"

    - name: Check if necessary packages are installed on Debian-based systems
      ansible.builtin.command: "dpkg -l {{ item }}"
      changed_when: false
      with_items: "{{ vnc_zsh_install_packages }}"
      register: dpkg_result
      failed_when: "'no packages found' in dpkg_result.stdout"
      when: asdf_os_family == 'debian'

    - name: Check if necessary packages are installed on redhat-based systems
      ansible.builtin.command: "dnf list installed {{ item }}"
      changed_when: false
      with_items: "{{ vnc_zsh_install_packages }}"
      register: dnf_result
      failed_when: "'no packages found' in dnf_result.stdout"
      when: asdf_os_family == 'redhat'

    - name: Confirm vnc passwd files exist for all vnc_zsh_users
      ansible.builtin.stat:
        path: "/home/{{ item.username }}/.vnc/passwd"
      with_items: "{{ vnc_zsh_users }}"

    - name: Simulate failed package installation
      block:
        - name: Rename package manager temporarily (Debian)
          ansible.builtin.command: mv /usr/bin/apt /usr/bin/apt_backup
          when: ansible_facts.os_family == 'Debian'
          changed_when: false

        - name: Rename package manager temporarily (RedHat)
          ansible.builtin.command: mv /usr/bin/dnf /usr/bin/dnf_backup
          when: ansible_facts.os_family == 'RedHat'
          changed_when: false

        - name: Run role to check error handling
          ansible.builtin.include_role:
            name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      rescue:
        - name: Restore package manager (Debian)
          ansible.builtin.command: mv /usr/bin/apt_backup /usr/bin/apt
          when: ansible_facts.os_family == 'Debian'
          changed_when: false

        - name: Restore package manager (RedHat)
          ansible.builtin.command: mv /usr/bin/dnf_backup /usr/bin/dnf
          when: ansible_facts.os_family == 'RedHat'
          changed_when: false
