---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: docker

platforms:
  - name: ubuntu-workstation
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../../../roles:${ANSIBLE_ROLES_PATH:-/etc/ansible/roles}"
  config_options:
    defaults:
      interpreter_python: auto_silent
      roles_path: ../../../../roles
  ansible_args:
    - --connection=docker
    - -v

verifier:
  name: ansible
