---
name: Pre-Commit
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
  # Run once a week (see https://crontab.guru)
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  pre-commit:
    name: Update pre-commit hooks and run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5
        with:
          python-version: "3.12.0"

      - name: Install dependencies
        run: python3 -m pip install ansible \
          ansible-lint \
          docker \
          molecule[docker] \
          pre-commit

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version: '1.22'

      - name: Install go module dependencies
        run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
          go install github.com/magefile/mage@latest

      - name: Install pre-commit
        run: python3 -m pip install pre-commit

      - name: Run go mod tidy - necessary to avoid errors with dependabot PRs
        run: pushd magefiles; go mod tidy; popd

      - name: Commit go.mod and go.sum changes to keep pre-commit happy
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add magefiles/go.mod magefiles/go.sum
          git diff --quiet && git diff --staged --quiet || \
            git commit -m "Update go.mod and go.sum"

      - name: Install pre-commit dependencies
        run: mage installDeps

      - name: Run pre-commit
        run: mage runPreCommit
